name: Bug Report
description: Report a bug or issue with nix-modules
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide the steps to reproduce the bug:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - NixOS version:
        - nixpkgs channel:
        - Nix modules version (commit hash):
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please include any relevant error messages or logs.
    validations:
      required: false

  - type: checklist
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have searched the existing issues and this bug has not been reported yet
        - label: I can reproduce the bug consistently
        - label: I am using the latest version of nix-modules
